apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Validate=false,Prune=false,Delete=false

resources:
- github.com/redhat-cop/gitops-catalog/advanced-cluster-management/operator/overlays/release-2.9
- github.com/redhat-cop/gitops-catalog/advanced-cluster-management/instance/base
