apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-gitops-mc
  namespace: openshift-gitops
spec:
  clusterSets:
  - global
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: gitops
          operator: Exists
        - key: gitops-repo
          operator: Exists
        - key: name
          operator: NotIn
          values: ["local-cluster"]
