apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gitops-policy-generator
policyDefaults:
  copyPolicyMetadata: false
  namespace: acm-policies
  remediationAction: enforce
  pruneObjectBehavior: DeleteIfCreated
placementBindingDefaults:
  name: "binding-policy-observability"
policies:
  - name: policy-acm-observability
    consolidateManifests: false
    manifests:
      - path: manifests/
    dependencies:
    - name: policy-odf-status
      namespace: "acm-policies"
  
  - name: policy-observability-gitops
    configurationPolicyAnnotations: {"policy.open-cluster-management.io/disable-templates": "true"}
    dependencies:
    - name: "policy-acm-observability"
      namespace: "acm-policies"
      compliance: "Compliant"
      kind: "Policy"
      apiVersion: "policy.open-cluster-management.io/v1"
    manifests:
      - path: custom/
policySets:
  - name: "observability"
    description: "Policy for enabling Observability"
    policies:
      - policy-acm-observability
      - policy-observability-gitops
    generatePolicySetPlacement: false
    placement:
      name: placement-hub
