apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: hub-preprocess-secret-populate
spec:
  remediationAction: enforce
  severity: low
  object-templates-raw: |
    - complianceType: mustnothave
      objectDefinition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: fake-policy-holder
          namespace: acm-policies
        data:
          fake: holder so policy is not generated empty

    {{$secrets := (lookup "v1" "Secret" "bsa-hub-source" "").items }}
    {{ range $obj := $secrets }}
    {{- if hasPrefix "hub-source-" $obj.metadata.name }}
    - complianceType: musthave
      objectDefinition:
        kind: Secret
        apiVersion: v1
        metadata:
          name: "{{ $obj.metadata.name }}"
          namespace: acm-policies
        data:
          preprocessed: dHJ1ZQ==
    {{ range $k, $v := $obj.data }}
          "{{$k}}": "{{$v}}"
    {{end}}
    {{end}}
    {{end}}
