apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: populate-secrets-in-all-clusters
spec:
  remediationAction: enforce
  severity: low
  object-templates-raw: |
    - complianceType: mustnothave
      objectDefinition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: fake-policy-holder
          namespace: bsa-user-10
        data:
          fake: holder so policy is not generated empty

    {{$secrets := (lookup "v1" "Secret" "bsa-source" "").items }}
    {{ range $obj := $secrets }}
    {{- if hasPrefix "source-" $obj.metadata.name }}
    - complianceType: musthave
      objectDefinition:
        kind: Secret
        apiVersion: v1
        metadata:
          name: "cloned-{{ $obj.metadata.name }}"
          namespace: bsa-user10
        data:
          populated: dHJ1ZQ==
    {{ range $k, $v := $obj.data }}
          "{{$k}}": "{{$v}}"
    {{end}}
    {{end}}
    {{end}}

    {{hub $secretsHub := (lookup "v1" "Secret" "acm-policies" "").items hub}}
    {{hub range $objHub := $secretsHub hub}}
    {{hub if hasPrefix "hub-source-" $objHub.metadata.name hub}}
    - complianceType: musthave
      objectDefinition:
        kind: Secret
        apiVersion: v1
        metadata:
          name: "cloned-{{hub $objHub.metadata.name hub}}"
          namespace: bsa-user11
        data:
          populated-from-hub: dHJ1ZQ==
    {{hub range $kHub, $vHub := $objHub.data hub}}
          "{{$kHub}}": "{{$vHub}}"
    {{hub end hub}}
    {{hub end hub}}
    {{hub end hub}}
