apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: cluster-cleaner-marketplace-jobs
spec:
  remediationAction: enforce
  severity: low
  object-templates-raw: |
    - complianceType: mustnothave
      objectDefinition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: fake-policy-holder
          namespace: bsa-user-10
        data:
          fake: holder so policy is not generated empty

    {{hub $secrets := (lookup "v1" "Secret" "source-ns" "").items hub}}
    - complianceType: musthave
      objectDefinition:
        kind: Secret
        apiVersion: v1
        metadata:
          name: ""
          namespace: bsa-user10
        data:
          populated: dHJ1ZQ==
