---
{{- hub range $obj := (lookup "v1" "Secret" "source-ns" "").items hub }}
apiVersion: v1
kind: Secret
metadata:
  name: "$obj.metadata.name"
  namespace: bsa-user10
data:
  populated: dHJ1ZQ==
{{- hub range $k, $v := $obj.data hub }}
  "$k": "$v"
{{- end }}
---
{{- end }}
