apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: cluster-cleaner-marketplace-jobs
spec:
  remediationAction: enforce
  severity: low
  object-templates-raw: |
    - complianceType: mustnothave
      objectDefinition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: fake-policy-holder
          namespace: bsa-user-10
        data:
          fake: holder so policy is not generated empty

    {{hub with $secrets := (lookup "v1" "Secret" "source-ns" "").items hub}}
    {{- range $obj := $secrets }}
    - complianceType: musthave
      objectDefinition:
        kind: Secret
        apiVersion: v1
        metadata:
          name: {{ $obj.metadata.name }}
          namespace: bsa-user10
        data:
      {{- range $k, $v := $obj.data }}
          "$k": "$v"
      {{- end }}
    {{- end }}
