apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-gatekeeper
  namespace: acm-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-policy-opa
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: PolicySet
  name: gatekeeper
