apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: kyverno-policy-generator
policyDefaults:
  configurationPolicyAnnotations: {"policy.open-cluster-management.io/disable-templates": "true"}
  policyAnnotations: {"argocd.argoproj.io/sync-options": "ServerSideApply=true"}
  namespace: acm-policies
  remediationAction: enforce
placementBindingDefaults:
  name: "binding-policy-kyverno"
policies:
  - name: policy-kyverno-install
    manifests:
      - path: install/
  - name: policy-kyverno-global-rules
    dependencies:
    - name: "policy-kyverno-install"
    manifests:
      - path: rules/
policySets:
  - name: "kyverno"
    description: "Policy for installing kyverno and applying kyverno policies"
    policies:
      - policy-kyverno-install
      - policy-kyverno-global-rules
    generatePolicySetPlacement: false
    placement:
      name: placement-policy-all
