apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bgd-app-set
  namespace: argocd
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-managed-clusters
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{name}}-bgd-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/christianh814/gitops-examples.git'
        targetRevision: HEAD
        path: bgd
      destination:
        server: '{{server}}'
        namespace: bgd
      ignoreDifferences:
      - jsonPointers:
        - /spec/host
        group: "*"
        kind: Route
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
