apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pull-app-set
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-gitops
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{name}}-pull-app'
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: 'true'
      annotations:
        argocd.argoproj.io/skip-reconcile: 'true'
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
    spec:
      project: default
      source:
        repoURL: 'https://github.com/mervani/acm-demo-managedcluster.git'
        targetRevision: HEAD
        path: example-app/overlays/ex2
      destination:
        server: https://kubernetes.default.svc
        namespace: bsa-pull-demo
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
