apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
spec:
  resourceTrackingMethod: annotation
  server:
    env:
      - name: ARGOCD_SERVER_ENABLE_GZIP
        value: 'true'
      - name: ARGOCD_SERVER_REPO_SERVER_TIMEOUT_SECONDS
        value: '120'
    autoscale:
      enabled: true
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 25m
        memory: 28Mi
    route:
      enabled: true
    service:
      type: ''
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 25m
        memory: 128Mi
  monitoring:
    enabled: false
  notifications:
    enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  initialSSHKnownHosts: {}
  resourceHealthChecks:
    - group: policy.open-cluster-management.io
      kind: Policy
      check: |
        hs = {}
        if obj.status ~= nil and obj.spec.disabled ~= nil and obj.spec.disabled == false then
          hs.status = "Healthy"
          hs.message = "Policy is disabled"
          return hs
        end
        if obj.status == nil or obj.status.compliant == nil then
          hs.status = "Progressing"
          hs.message = "Waiting for the status to be reported"
          return hs
        end
        if obj.status.compliant == "Compliant" then
          hs.status = "Healthy"
        else
          hs.status = "Degraded"
        end
        noncompliants = {}
        if obj.status.status ~= nil then
          -- "root" policy
          for i, entry in ipairs(obj.status.status) do
            if entry.compliant ~= "Compliant" then
              table.insert(noncompliants, entry.clustername)
            end
          end
          if #noncompliants == 0 then
            hs.message = "All clusters are compliant"
          else
            hs.message = "NonCompliant clusters: " .. table.concat(noncompliants, ", ")
          end
        elseif obj.status.details ~= nil then
          -- "replicated" policy
          for i, entry in ipairs(obj.status.details) do
            if entry.compliant ~= "Compliant" then
              table.insert(noncompliants, entry.templateMeta.name)
            end
          end
          if #noncompliants == 0 then
            hs.message = "All templates are compliant"
          else
            hs.message = "NonCompliant templates: " .. table.concat(noncompliants, ", ")
          end
        end
        return hs
    - group: argoproj.io
      kind: Application
      check: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
    - group: operators.coreos.com
      kind: Subscription
      check: |
        health_status = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            numDegraded = 0
            numPending = 0
            msg = ""
            for i, condition in pairs(obj.status.conditions) do
              msg = msg .. i .. ": " .. condition.type .. " | " .. condition.status .. "\n"
              if condition.type == "InstallPlanPending" and condition.status == "True" then
                numPending = numPending + 1
              elseif (condition.type == "InstallPlanMissing" and condition.reason ~= "ReferencedInstallPlanNotFound") then
                numDegraded = numDegraded + 1
              elseif (condition.type == "CatalogSourcesUnhealthy" or condition.type == "InstallPlanFailed" or condition.type == "ResolutionFailed") and condition.status == "True" then
                numDegraded = numDegraded + 1
              end
            end
            if numDegraded == 0 and numPending == 0 then
              health_status.status = "Healthy"
              health_status.message = msg
              return health_status
            elseif numPending > 0 and numDegraded == 0 then
              health_status.status = "Progressing"
              health_status.message = "An install plan for a subscription is pending installation"
              return health_status
            else
              health_status.status = "Degraded"
              health_status.message = msg
              return health_status
            end
          end
        end
        health_status.status = "Progressing"
        health_status.message = "An install plan for a subscription is pending installation"
        return health_status
    - group: operators.coreos.com
      kind: InstallPlan
      check: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.phase ~= nil then
            if obj.status.phase == "Complete" then
              hs.status = "Healthy"
              hs.message = obj.status.phase
              return hs
            end
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for InstallPlan to complete"
        return hs
    - group: platform.stackrox.io
      kind: Central
      check: |
        hs = {}
        if obj.status ~= nil and obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.status == "True" or condition.reason == "InstallSuccessful" or condition.reason == "UpgradeSuccessful" then
                  hs.status = "Healthy"
                  hs.message = "Install Successful"
                  return hs
              end
            end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for Central to deploy."
        return hs
    - group: image.openshift.io
      kind: ImageStream
      check: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.tags ~= nil then
            numTags = 0
            for _ , item in pairs(obj.status.tags) do
              numTags = numTags + 1
              numItems = 0
              if item.tags ~= nil then
                for _ , item in pairs(item.tags) do
                  numItems = numItems + 1
                end
                if numItems == 0 then
                  return hs
                end
              end
            end
            if numTags > 0 then
              hs.status = "Healthy"
              hs.message = "ImageStream has tags resolved"
              return hs
            end
          end
        end
        return hs
    - group: build.openshift.io
      kind: Build
      check: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.phase ~= nil then
            if obj.status.phase == "Complete" then
              hs.status = "Healthy"
              hs.message = obj.status.phase
              return hs
            end
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for Build to complete"
        return hs
    - kind: PersistentVolumeClaim
      group: ""
      check: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.phase ~= nil then
            if obj.status.phase == "Pending" then
              hs.status = "Healthy"
              hs.message = obj.status.phase
              return hs
            end
            if obj.status.phase == "Bound" then
              hs.status = "Healthy"
              hs.message = obj.status.phase
              return hs
            end
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for PVC"
        return hs
  resourceIgnoreDifferences:
    resourceIdentifiers:
      - group: route.openshift.io
        kind: Route
        customization:
          jsonPointers:
            - /status/ingress
            - /metadata/annotations
      - group: quay.redhat.com
        kind: QuayRegistry
        customization:
          jsonPointers:
            - /status/ingress
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 25m
          memory: 28Mi
    provider: dex
  applicationSet:
    resources:
      limits:
        cpu: '2'
        memory: 1Gi
      requests:
        cpu: 25m
        memory: 51Mi
    webhookServer:
      ingress:
        enabled: false
      route:
        enabled: false
  rbac:
    defaultPolicy: 'role:none'
    policy: |
      # Access Control 
      p, role:none, applications, get, */*, deny
      p, role:none, certificates, get, *, deny
      p, role:none, clusters, get, *, deny
      p, role:none, repositories, get, *, deny
      p, role:none, projects, get, *, deny
      p, role:none, accounts, get, *, deny
      p, role:none, gpgkeys, get, *, deny
      p, pipeline, applications, get, */*,allow
      p, pipeline, applications, sync, */*,allow
      p, pipeline, projects, get, *, allow
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
    scopes: '[groups]'
  extraConfig:
    accounts.pipeline: apiKey
    resource.customizations.ignoreResourceUpdates.all: |
      jsonPointers:
      - /status
    resource.ignoreResourceUpdatesEnabled: 'true'
    resource.compareoptions: |
      ignoreResourceStatusField: all
  repo:
    sidecarContainers:
      - command:
          - /var/run/argocd/argocd-cmp-server
        env:
          - name: KUSTOMIZE_PLUGIN_HOME
            value: /etc/kustomize/plugin
        image: 'quay.io/rhn_gps_mileri/policy-gen-tool:latest'
        imagePullPolicy: Always
        name: policy-gen-plugin
        securityContext:
          runAsNonRoot: true
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            name: cmp-cm
            subPath: plugin.yaml
    volumes:
      - configMap:
          name: cmp-cm
        name: cmp-cm
    resources:
      limits:
        cpu: '2'
        memory: 2Gi
      requests:
        cpu: 50m
        memory: 51Mi
  resourceExclusions: |
    - apiGroups:
      - policy.open-cluster-management.io
      clusters:
      - '*'
      kinds:
      - ConfigurationPolicy      
    - apiGroups:
      - compliance.openshift.io
      kinds:
      - ComplianceCheckResult
      - ComplianceRemediation  
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
  ha:
    enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 25m
        memory: 28Mi
  kustomizeBuildOptions: '--enable-alpha-plugins --enable-helm'
  tls:
    ca: {}
  redis:
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: 25m
        memory: 56Mi
  controller:
    env:
      - name: ARGOCD_APPLICATION_CONTROLLER_REPO_SERVER_TIMEOUT_SECONDS
        value: '120'
      - name: ARGOCD_K8S_CLIENT_QPS
        value: '100'
      - name: ARGOCD_K8S_CLIENT_BURST
        value: '200'
    logLevel: info
    processors: {}
    resources:
      limits:
        cpu: '4'
        memory: 8Gi
      requests:
        cpu: 50m
        memory: 20Mi
    sharding: {}
