kind: ConfigMap
apiVersion: v1
metadata:
  name: thanos-ruler-custom-rules
  namespace: open-cluster-management-observability
data:
  custom_rules.yaml: |
    groups:
      - name: cluster-health
        rules:
        - alert: MemoryRequested-45
          annotations:
            summary: Notify when the total memory requested in the clusters is greater than 45%.
            description: "The cluster {{ $labels.cluster }} has more than 45% of the memory requested."
          expr: |
            cluster:memory_requested:ratio > 0.45
          for: 5s
          labels:
            cluster: "{{ $labels.cluster }}"
            severity: warning
