kind: ConfigMap
apiVersion: v1
metadata:
  name: thanos-ruler-custom-rules
  namespace: open-cluster-management-observability
data:
  custom_rules.yaml: |
    groups:
      - name: cluster-health
        rules:
        - alert: MemoryRequested-45
          annotations:
            summary: Notify when the total memory requested in the clusters is greater than 45%.
            description: "The cluster {{ $labels.cluster }} has more than 45% of the memory requested."
          expr: |
            cluster:memory_requested:ratio > 0.45
          for: 5s
          labels:
            cluster: "{{ $labels.cluster }}"
            severity: warning
        - alert: ClusterCPUReq-60
          annotations:
            summary: Notify when CPU requests on a cluster are greater than the defined utilization limit
            description: "The cluster {{ $labels.cluster }} has an elevated percentage of CPU requests: {{ $labels.clusterID }}."
          expr: |
            sum(namespace_cpu:kube_pod_container_resource_requests:sum) by (clusterID, cluster) / sum(kube_node_status_allocatable{resource="cpu"}) by (clusterID, cluster) > 0.6
          for: 5s
          labels:
            cluster: "{{ $labels.cluster }}"
            severity: critical
