apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-devops-ns-label
  annotations:
    policies.kyverno.io/title: Validate Team Namespace Label
    policies.kyverno.io/category: Multitenancy, Multicluster-Management
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.7.0
    policies.kyverno.io/minversion: 1.7.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: Group
    policies.kyverno.io/description: >-
      Denies the creation of a namespace if the label of the namespace does
      not follow a specific naming defined by the cluster admins.
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: namespace-label
    match:
      any:
      - resources:
          kinds:
          - Namespace
          - ProjectRequest
          - Project
    exclude:
      any:
      - subjects:
        - kind: Group
          name: "devops-group"
      - clusterRoles:
        - cluster-admin
    preconditions:
      any:
      - key: "{{request.operation}}"
        operator: AnyIn
        value:
        - CREATE
        - UPDATE
    validate:
      message: The framework label is required to create the namespace
      pattern:
        metadata:
          labels:
            framework: "?*"
