apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-demos
  namespace: acm-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-policy-all
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: PolicySet
  name: demo-policies
