apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: kyverno-policy-generator
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
placementBindingDefaults:
  name: "binding-policy-demos"
policies:
  - name: policy-secret-populate
    manifests:
      - path: examples/ns.yaml
      - path: examples/secret-populate.yaml
  - name: policy-ns-label-check
    remediationAction: inform
    manifests:
      - path: examples/ns-label.yaml
    namespaceSelector:
      include:
        - bsa-*
policySets:
  - name: "demo-policies"
    description: "Policy for showing acm capabilities"
    policies:
      - policy-secret-populate
      - policy-ns-label-check
    generatePolicySetPlacement: false
    placement:
      name: placement-policy-all
